Organize a bit

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -15,11 +15,28 @@ http://benalman.com/about/license/
 HELP
 exit; fi
 
+# Variables {{{
+
+repo_dir="$HOME/distro"
+repo_git="git..."
+
+# If backups are needed, this is where they'll go.
+backup_dir="$HOME/./backups/$(date "+%Y_%m_%d-%H_%M_%S")/"
+backup=
+
+# }}}
+# Helpers {{{
+
 # Logging stuff.
 function e_header()   { echo -e "\n\033[1m$@\033[0m"; }
 function e_success()  { echo -e " \033[1;32m✔\033[0m  $@"; }
 function e_error()    { echo -e " \033[1;31m✖\033[0m  $@"; }
 function e_arrow()    { echo -e " \033[1;33m➜\033[0m  $@"; }
+
+function die()        { e_error "$@"; exit 1; } >&2
+
+# }}}
+# General functions {{{
 
 # Given a list of desired items and installed items, return a list
 # of uninstalled items. Arrays in bash are insane (not in a good way).
@@ -58,39 +75,10 @@ function skip() {
   fi
 }
 
-# Initialize.
-function init_do() {
-  source "$2"
-}
-
-# Copy files.
-function copy_header() { e_header "Copying files into home directory"; }
-function copy_test() {
-  if [[ -e "$2" && ! "$(cmp "$1" "$2" 2> /dev/null)" ]]; then
-    echo "same file"
-  elif [[ "$1" -ot "$2" ]]; then
-    echo "destination file newer"
-  fi
-}
-function copy_do() {
-  e_success "Copying ~/$1."
-  cp "$2" ~/
-}
-
-# Link files.
-function link_header() { e_header "Linking files into home directory"; }
-function link_test() {
-  [[ "$1" -ef "$2" ]] && echo "same file"
-}
-function link_do() {
-  e_success "Linking ~/$1."
-  ln -sf ${2#$HOME/} ~/
-}
-
 # Copy, link, init, etc.
 function do_stuff() {
   local base dest skip
-  local files=(~/.dotfiles/$1/*)
+  local files=($repo_dir/$1/*)
   # No files? abort.
   if (( ${#files[@]} == 0 )); then return; fi
   # Run _header function only if declared.
@@ -123,64 +111,96 @@ function do_stuff() {
   done
 }
 
+# }}}
+# Init functions {{{
+
+# Initialize.
+function init_do() {
+  source "$2"
+}
+
+# }}}
+# Copy functions {{{
+
+# Copy files.
+function copy_header() { e_header "Copying files into home directory"; }
+function copy_test() {
+  if [[ -e "$2" && ! "$(cmp "$1" "$2" 2> /dev/null)" ]]; then
+    echo "same file"
+  elif [[ "$1" -ot "$2" ]]; then
+    echo "destination file newer"
+  fi
+}
+function copy_do() {
+  e_success "Copying ~/$1."
+  cp "$2" ~/
+}
+
+# }}}
+# Link functions {{{
+
+# Link files.
+function link_header() { e_header "Linking files into home directory"; }
+function link_test() {
+  [[ "$1" -ef "$2" ]] && echo "same file"
+}
+function link_do() {
+  e_success "Linking ~/$1."
+  ln -sf ${2#$HOME/} ~/
+}
+
+# }}}
+# Setup {{{
+
 # Enough with the functions, let's do stuff.
+
+# Verify the environment
+[[ $(cat /etc/issue 2> /dev/null) =~ Ubuntu ]] || die "Not running ubuntu"
+[[ $(/usr/bin/id -u) == 0 ]] || die "Not running as root"
 
 # If Git is not installed...
 if [[ ! "$(type -P git)" ]]; then
-  # OSX
-  if [[ "$OSTYPE" =~ ^darwin ]]; then
-    # It's easiest to get Git via Homebrew, so get that first.
-    if [[ ! "$(type -P brew)" ]]; then
-      e_header "Installing Homebrew"
-      /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
-      brew update
-    fi
-    # If Homebrew was installed, install Git.
-    if [[ "$(type -P brew)" ]]; then
-      e_header "Installing Git"
-      brew install git
-    fi
-  # Ubuntu.
-  elif [[ "$(cat /etc/issue 2> /dev/null)" =~ Ubuntu ]]; then
-    # Git is fairly easy.
-    e_header "Installing Git"
-    sudo apt-get -qq install git-core
-  fi
+  e_header "Installing Git"
+  sudo apt-get -qq install git-core
 fi
 
 # If Git isn't installed by now, something exploded. We gots to quit!
 if [[ ! "$(type -P git)" ]]; then
-  e_error "Git should be installed. It isn't. Aborting."
-  exit 1
+  die "Git should be installed. It isn't. Aborting."
 fi
 
 # Initialize.
-if [[ ! -d ~/.dotfiles ]]; then
+if [[ ! -d $repo_dir ]]; then
   new_dotfiles_install=1
-  # ~/.dotfiles doesn't exist? Clone it!
-  e_header "Downloading dotfiles"
-  git clone --recursive git://github.com/cowboy/dotfiles.git ~/.dotfiles
-  cd ~/.dotfiles
+  # repository doesn't exist? Clone it!
+  e_header "Downloading repository"
+  git clone --recursive "$repo_git" "$repo_dir" \
+    && cd "$repo_dir"
 else
   # Make sure we have the latest files.
   e_header "Updating dotfiles"
-  cd ~/.dotfiles
-  git pull
-  git submodule update --init --recursive --quiet
+  cd "$repo_dir" \
+    && git pull \
+    && git submodule update --init --recursive --quiet
+fi
+if [[ $? != 0 ]]; then
+  die "Failed fetching the latest version of the distro repository"
 fi
 
 # Tweak file globbing.
 shopt -s dotglob
 shopt -s nullglob
 
-# If backups are needed, this is where they'll go.
-backup_dir="$HOME/.dotfiles/backups/$(date "+%Y_%m_%d-%H_%M_%S")/"
-backup=
+# }}}
+# Do stuff {{{
 
 # Execute code for each file in these subdirectories.
 do_stuff "init"
 do_stuff "copy"
 do_stuff "link"
+
+# }}}
+# Finish up {{{
 
 # Alert if backups were made.
 if [[ "$backup" ]]; then
@@ -195,3 +215,5 @@ fi
 
 # All done!
 e_header "All done!"
+
+# }}}
